<?php

/**
 * Implements hook_theme().
 */
function branchee_block_theme($existing, $type, $theme, $path) {
  $theme = [];

  $theme['branchee_menu_block'] = [
    'variables' => [
      'menu' => '',
      'second_menu' => '',
      'branchee_theme' => '',
    ],
  ];

  return $theme;
}

/**
 * Add menu level classes to the menu items in the generated menu tree
 */
function branchee_block_add_menu_class(&$tree, $level) {
  if (isset($tree['#items'])) {
    $menu_items = &$tree['#items'];
  } else {
    $menu_items = &$tree;
  }

  // Loop through the menu items adding in the current level as a class
  // Recurse through child menus.
  // Add active class to the menu items in the current path.
  foreach ($menu_items as &$menu_item) {
    $menu_item['attributes']->addClass('branchee-level-' . $level);

    $current_path = \Drupal::request()->getRequestUri();
    if ($menu_item['url']->toString() == $current_path) {
      // Add active link.
      $menu_item['attributes']->addClass('active');
    }
    if ($menu_item['below']) {
      branchee_block_add_menu_class($menu_item['below'], $level+1);
    }
  }
}
